Fatal error activating with old version of PublishPress Authors
Since vendor/publishpress/wordpress-banners is already included by the composer autoloader, don't manually load it.

Relying on the autoloader eliminates this conflict with older versions of PublishPress Authors:

Fatal error: Cannot declare class PublishPress\WordPressBanners\BannersMain, because the name is already in use in /www/kinsta/public/publishpress/wp-content/plugins/publishpress-authors/vendor/publishpress/wordpress-banners/BannersMain.php on line 29